profiles:
  default:
    - .bashrc
    - .codex/agents
    - .codex/config.toml
    - .codex/hooks
    - .codex/hooks.json
    - .codex/rules
    - .codex/skills
    - .profile
    - .zlogin
    - .zprofile
    - .zshenv
    - .zshrc
    - .gitconfig
    - .git.scmbrc
    - .scmbrc
    - .tmux.conf
    - .vimrc
    - .config/fish
    - .config/git
    - .config/iterm2
    - .config/nvim
    - .config/uv
  work:
    - .bashrc
    - .codex/agents
    - .codex/config.toml
    - .codex/hooks
    - .codex/hooks.json
    - .codex/rules
    - .codex/skills
    - .profile
    - .zlogin
    - .zprofile
    - .zshenv
    - .gitconfig
    - .git.scmbrc
    - .scmbrc
    - .tmux.conf
    - .vimrc
    - .config/fish
    - .config/git
    - .config/iterm2
    - .config/nvim
    - .config/uv
